# ğŸ“„ pubspec.yaml

name: jelamvp01
description: "L'app qui envoie de l'amour â¤ï¸"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.0
  firebase_analytics: ^10.8.0

  share_plus: ^7.2.1
  flutter_local_notifications: ^17.2.4
  device_info_plus: ^10.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/app_icon.png"

flutter:
  uses-material-design: true
